### ISSUE TITLE
Dynamic serial port

### ISSUE THREAD

**Issue by scorpioRED** [Desionlab/node-cashcode-bv#5]
Hi! Did you think to add automatic serial port connection ?
I mean to set port number automatically .
Something like try /dev/ttyS0(or COM1 for windows) if erro - try /dev/ttyS1 (or COM2 for windows).
I have try to do that, but I don’t understand where I have to check it and restart serialport

**Comment by fenixphp** [comment]
I don't remember exactly, if I am not mistaken, then you need:
1) Track com port errors.
2) Track the timeout events and checksum errors in order to distinguish the bill acceptor from the other peripheral connected to the computer.

For a long time I did not work with this component a bit later, I’m trying to give something specifically.
